---
title: "Data_Cleaning"
output: html_document
date: "2023-12-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tseries)
library(ggplot2)
library(tidyverse)
library(reshape2)
library(car)

```

Reading in the documents I need:
```{r}
brent_crude_prices<- read_excel("brent_crude_prices.xlsx")
co2_emissions_data<-read.csv("co2_emission.csv")
ftse<- read.csv("FTSE 100 Historical Data.csv")
eu_ets_data<-read_excel("EU-ETS-data.xlsx")
```

Converting dates to the right format so I can join them:

```{r}
eu_ets_data$Date<- as.Date(eu_ets_data$Date)
brent_crude_prices$Date<- as.Date(brent_crude_prices$Date)
ftse$Date<- as.Date(ftse$Date)
```

Joining the three data frames:

```{r}
auction_and_oil<- merge(x=eu_ets_data,y=brent_crude_prices, 
                         by="Date", all.x=TRUE) 

auction_and_oil<-auction_and_oil |> filter(is.na(auction_and_oil$`Europe Brent Spot Price FOB (Dollars per Barrel)`)==FALSE)

oil_prices<- auction_and_oil$`Europe Brent Spot Price FOB (Dollars per Barrel)`
pacf(oil_prices, lag=10, pl=TRUE)

ets_stock_and_oil_data<- merge(x=auction_and_oil, y= ftse, by='Date', all.x=TRUE)
```

Now we need to clean the ets_stock and oil data so we can get an appropriate lag and check autocorrelations for each type of data:
```{r}
#First let's change auction name to just have EU, DE, PL or EUAA:

ets_stock_and_oil_data<- ets_stock_and_oil_data |> mutate(
                AuctionType = ifelse(str_detect(`Auction Name`, "EUAA")==TRUE,
                                                                        "EUAA",
                                                    str_sub(`Auction Name`,-2,)
), .after=`Auction Name`)
```

So let's test autocorrelation for price, co2, etc each subset of the auctions. Starting with EU type:
```{r}
EU_only_auction<- ets_stock_and_oil_data |> filter(AuctionType=="EU") |> filter(
                                          is.na(`Auction Price €/tCO2`)==FALSE
)
eu_only_auction_price<-EU_only_auction$`Auction Price €/tCO2`

pacf(eu_only_auction_price, lag=10, pl=TRUE)


lag<- EU_only_auction$`Auction Price €/tCO2`[2:length(EU_only_auction$`Auction Price €/tCO2`)-2]
lag<- c(0,lag,0)
lag[length(lag)]<-0
EU_only_with_lag<- EU_only_auction |> mutate(
                                          lag= lag, .after=`Auction Price €/tCO2`
)

EU_only_auction_variables_fit<- glm(`Auction Price €/tCO2`~ lag+ `Auction Volume tCO2`+ `Average number of bids per bidder`,
                            family=gaussian, data=EU_only_with_lag)

durbinWatsonTest(EU_only_auction_variables_fit)
```



